#!/bin/bash

export APP_DEPLOYMENT_DIRECTORY=$(pwd)/bin/Release/net10.0/publish

export CORECLR_ENABLE_PROFILING=1
export CORECLR_PROFILER={36032161-FFC0-4B61-B559-F6C5D41BAE5A}
export CORECLR_PROFILER_PATH=$APP_DEPLOYMENT_DIRECTORY/newrelic/libNewRelicProfiler.so
export CORECLR_NEWRELIC_HOME=$APP_DEPLOYMENT_DIRECTORY/newrelic
export NEW_RELIC_LICENSE_KEY="$NEW_RELIC_LICENSE_KEY"
export NEW_RELIC_APP_NAME=ai-o11y-agent-framework
export NEW_RELIC_LOG=$APP_DEPLOYMENT_DIRECTORY/newrelic/logs/agent.log
export NEW_RELIC_LOG_ENABLED=true
export NEWRELIC_LOG_LEVEL=info
#export NEWRELIC_PROFILER_LOG_DIRECTORY=$APP_DEPLOYMENT_DIRECTORY/newrelic/logs
export NEW_RELIC_AI_MONITORING_ENABLED=true
export NEW_RELIC_AI_MONITORING_RECORD_CONTENT_ENABLED=true

dotnet run $APP_DEPLOYMENT_DIRECTORY/ai-o11y-agent-framework.dll
